theme: jekyll-theme-cayman

## Overview
A to-do list that allows the user to dynamically create a list, strike through items on the list and delete the items on the list.
<br>

## Live Demo
To view the web app go to [https://prgip06.github.io/to-do-List/](https://prgip06.github.io/to-do-List/)
<br>
